config/routes.rb
Rails.application.routes.draw do
  # login
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'mypage/:id/edit', to: 'sessions#edit', as: 'edit_mypage'
  get 'mypage/:id', to: 'sessions#show', as: 'mypage'
  patch 'mypage/:id', to: 'sessions#update' 
  put 'mypage/:id', to: 'sessions#update'
  
  #likes
  get 'likes' => "likes#index"
  post 'likes' =>"likes#post_create"
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  
  #search
  get 'search' => "searches#search"
  post 'search' =>"searches#create"
  
  #good
  get 'good' => "goods#good" 
  post 'good' => 'goods#create'
  
  #admin
  namespace :admin do
    resources :users
  end
  
  resources :posts 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
  
  enum status: { public: 0, private: 1 }, _prefix: true
  
  scope :display_list, -> (category, status) {
    if category != "none"
      where(category_id: category).status_public.order(created_at: :desc)
    else
      status_public.order(created_at: :desc)
    end
  }
  
  belongs_to :category
  
  has_many :likes, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  
  def index
    @posts = Post.display_list(category_params, status)
    @categories = Category.all
    @category = Category.request_category(category_params)
    @likesuser = User.find_by(id: session[:user_id])
  end

  def show
  end

  def new
    @post = Post.new
    @categories = Category.all
  end

  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.js { flash.now[:notice] = "投稿に成功しました" }
      else
        @false = "投稿に失敗しました"
      end
    end
  end

  def destroy
    @post.destroy
    redirect_to admin_user_path(session[:user_id]), notice: "削除しました"
  end
  
  def category_params
    params[:category].present? ? params[:category]
                               : "none"
  end
  
  private
    def set_post
      @post = Post.find(params[:id])
    end
  
    def post_params
      params.permit( :content, :status, :guest, :user_id, :category_id )
    end
    
    def update_params
      params.require(:post).permit(:content, :status, :guest, :user_id, :category_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div id="post_<%= post.id %>">
  <div class="post">
    <p>
      id: <%= post.guest %>
    </p>
    <p>
      <%= safe_join(post.content.split("\n"),tag(:br)) %>
    </p>
    <div class="likes-display">
      <div><p>愚痴の種類: <%= post.category.name %></p></div>
      <div>
        <% if session[:user_id] %>
          <% if User.find_by(id: session[:user_id]).liked_by?(post.id) %>
            <%= link_to  destroy_like_path(post), method: :DELETE, remote: true  do %>
              <i class="fas fa-heart unlike-btn"></i>
            <% end %>
            <%= post.likes.count %>
          <% else %>
            <%= link_to  create_like_path(post), method: :POST, remote: true do %>
              <i class="far fa-heart like-btn"></i>
            <% end %>
            <%= post.likes.count %>
          <% end %>
        <% else %>
          <%= link_to login_path do %>
            <i class="far fa-heart like-btn"></i>
          <% end %>
          <%= post.likes.count %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/create.js.erb
$('#meassages').prepend("<%= j(render @post) %>");
$('textarea').val('');
$('.popup').fadeOut();

app/views/posts/index.html.erb
<%= render "layouts/header" %>
<p id="notice"><%= notice %></p>
<div class="post-contents wrapper">
  <article>
    <div class="post-background">
      <% if @category.present? %>
        <h3><%= link_to "愚痴", "/", category: @major_category_name %> > <%= @category.name %></h3>
        <h1><%= @category.name %>の愚痴一覧<%= @posts.count %>件</h1>
      <% else %>
        <h1>愚痴一覧</h1>
      <% end %>
      <div id="meassages">
        <%= render @posts %>
      </div>
    </div>
  </article>
  <aside>
    <div class="post-background">
      管理人挨拶
      <%= image_tag "/images/animal_koutei_penguin_hina.png", class: "admin-logo" %>
      <p>こんにちは denunce管理人です。</p>
      <p>snsにかけないことや、普段たまっている愚痴をここで発散しませんか？</p>
      <p>あなたの日頃の愚痴を投稿して、ストレスを吹き飛ばしましょう！！</p>
    </div>
    <br>
    <div class="post-background">
      <h2 style="color: red;">このサイトの使い方</h2>
      <P>このサイトはログインせずに投稿することが可能です</P>
      <P>ただログインしていただくと、投稿していただいた投稿を管理することができます！</P>
      <P>(ログイン前に投稿していただいた投稿は表示することはできません(´;ω;｀))</P>
      <P>さらに他の投稿にいいねをすることができ、愚痴を共感することが可能になります</P>
      <P>その他にカテゴリー別に投稿割合が見れたりして、自分の愚痴がどのカテゴリーが多いか、知ることができます！</P>
      <P>ご興味ありましたら、ログインしてみてください！</P>
      <P>よろしくお願いします！！！</P>
    </div>
    <br>
    <div class="post-background">
      <p>愚痴の種類</p>
      <% @categories.each do |category| %>
        <p><%= link_to "#{category.name}", posts_path(category: category.id) %></p>
      <% end %> 
    </div>
    <br>
    <div class="post-background">広告</div>
  </aside>
</div>

app/views/posts/new.js.erb
$('.popup').fadeIn();

$('.js-modal-close').on('click',function(){
  $('.popup').fadeOut();
});

app/views/posts/search.html.erb
<%= render "layouts/header" %>
<p id="notice"><%= notice %></p>
<div class="post-contents wrapper">
  <article>
    <div class="post-background">
      <H1>愚痴一覧</H1>
      <div id="meassages">
        <%= render @posts %>
      </div>
    </div>
  </article>
  <aside>
    <div class="post-background">
      管理人挨拶
      <%= image_tag "/images/animal_koutei_penguin_hina.png", class: "admin-logo" %>
      <p>こんにちは denunce管理人です。</p>
      <p>snsにかけないことや、普段たまっている愚痴をここで発散しませんか？</p>
      <p>あなたの日頃の愚痴を投稿して、ストレスを吹き飛ばしましょう！！</p>
    </div>
    <br>
    <div class="post-background">
      <h2 style="color: red;">このサイトの使い方</h2>
      <P>このサイトはログインせずに投稿することが可能です</P>
      <P>ただログインしていただくと、投稿していただいた投稿を管理することができます！</P>
      <P>(ログイン前に投稿していただいた投稿は表示することはできません(´;ω;｀))</P>
      <P>さらに他の投稿にいいねをすることができ、愚痴を共感することが可能になります</P>
      <P>その他にカテゴリー別に投稿割合が見れたりして、自分の愚痴がどのカテゴリーが多いか、知ることができます！</P>
      <P>ご興味ありましたら、ログインしてみてください！</P>
      <P>よろしくお願いします！！！</P>
    </div>
    <br>
    <div class="post-background">
      <p>愚痴の種類</p>
      <% @categories.each do |category| %>
        <p><%= link_to "#{category.name}", posts_path(category: category.id) %></p>
      <% end %> 
    </div>
    <br>
    <div class="post-background">広告</div>
  </aside>
</div>