config/routes.rb
Rails.application.routes.draw do
  # login
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'mypage/:id/edit', to: 'sessions#edit', as: 'edit_mypage'
  get 'mypage/:id', to: 'sessions#show', as: 'mypage'
  patch 'mypage/:id', to: 'sessions#update' 
  put 'mypage/:id', to: 'sessions#update'
  
  #likes
  get 'likes' => "likes#index"
  post 'likes' =>"likes#post_create"
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  
  #search
  get 'search' => "searches#search"
  post 'search' =>"searches#create"
  
  #good
  get 'good' => "goods#good" 
  post 'good' => 'goods#create'
  
  #admin
  namespace :admin do
    resources :users
  end
  
  resources :posts 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many :likes, dependent: :destroy
  
  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end
  
  validates :nickname, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    @user.guest = @guest.guest
    if @user.save
      @post = Post.where(guest: session[:guest])
      @post.each do |post|
        post.user_id = session[:user_id]
        post.save
      end
      redirect_to login_path, notice: "「#{@user.nickname}」を登録しました！ ログインしてください！"
    else
      render :new
    end
  end

  def show
    @posts = Post.where(user_id: @user.id).order(created_at: :desc)
    @likes = Like.where(user_id: @user.id).order(created_at: :desc)
    @categories = Category.all
  end

  def index
    @users = User.all
    @posts = Post.where(user_id: nil)
    @user = User.new
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザ「#{@user.nickname}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.where(user_id: @user.id)
    if @post.present?
      @post.delete_all
    end
    @user.destroy
    reset_session
    redirect_to root_path, notice: "ユーザ「#{@user.nickname}」を削除しました。"
  end

  
  private
  
    def user_params
      params.require(:user).permit(:nickname, :email, :admin, :password, :password_confirmation)
    end
    
    def set_user
      @user = User.find_by(id: params[:id])
      redirect_to(admin_user_path(session[:user_id]), alert: "あなたのアカウントではありません") if @user.blank?
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="text-center">
  <div class="form-all">
    <%= form_with model: [:admin, @user], local: true do |f|%>
      <div class="form-group">
        <%= f.label :nickname, '名前' %>
        <%= f.text_field :nickname, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :email, 'メールアドレス ' %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
  
      <% if session[:user_id] %>
        <div class="form-group">
          <%= f.label :admin, class: 'form-check-label' do %>
            <%= f.check_box :admin, class: 'form-check-input' %>管理者権限
          <% end %>
        </div>
      <% end %>
  
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード(確認)' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
  
      <%= f.submit '登録する', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<div class="text-center">
  <div class="form-all">
    <p id="alert"><%= alert %></p>
    
    <h1><a><%= image_tag "/images/denunce.png", class: "logo" %></a></h1>
    <h1>ユーザー編集</h1>
    
    <%= form_with model: [:admin, @user], local: true do |f|%>
      <div class="form-group">
        <%= f.label :nickname, '名前' %>
        <%= f.text_field :nickname, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :email, 'メールアドレス ' %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
  
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード(確認)' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
  
      <%= f.submit '更新する', class: 'form-btn2' %>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<h1>ユーザー登録</h1>
<div>
  <table>
    <thead>
      <tr>
        <th><%= User.human_attribute_name(:nickname) %></th>
        <th><%= User.human_attribute_name(:email) %></th>
        <th><%= User.human_attribute_name(:admin) %></th>
        <th><%= User.human_attribute_name(:created_at) %></th>
        <th><%= User.human_attribute_name(:updated_at) %></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.nickname, [:admin, user] %></td>
        <td><%= user.email %></td>
        <td><%= user.admin? ? 'あり' : 'なし' %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <td>
          <%= link_to 'MYページ', admin_user_path(user) %>
          <%= link_to '編集', edit_admin_user_path(user) %>
          <%= link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザ「#{user.nickname}」を削除します。よろしいですか？" } %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<h1>投稿一覧</h1>

<% @posts.each do |post| %>
  <div class="post-display">
    <div><%= safe_join(post.content.split("\n"),tag(:br)) %></div>
    <div>
      <%= link_to post, method: :delete, data: { confirm: '削除していいですか?' } do %>
        <i class="fas fa-trash-alt"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/users/new.html.erb
<div class="text-center">
  <div class="form-all">
    <p id="alert"><%= alert %></p>
    <h1><a href="/"><%= image_tag "/images/denunce.png", class: "logo" %></a></h1> 
    <h1>ユーザー登録</h1>
    
    <%= form_with model: [:admin, @user], local: true do |f|%>
      <div class="form-group">
        <%= f.label :nickname, '名前', class: "label-hidden" %>
        <%= f.text_field :nickname, class: 'form-control', placeholder: "ニックネーム", autocomplete: "off" %>
      </div>
  
      <div class="form-group">
        <%= f.label :email, 'メールアドレス', class: "label-hidden" %>
        <%= f.text_field :email, class: 'form-control', placeholder: "メールアドレス", autocomplete: "off" %>
      </div>
  
      <% if session[:user_id] %>
        <div class="form-group">
          <%= f.label :admin, class: 'form-check-label' do %>
            <%= f.check_box :admin, class: 'form-check-input' %>管理者権限
          <% end %>
        </div>
      <% end %>
  
      <div class="form-group">
        <%= f.label :password, 'パスワード', class: "label-hidden" %>
        <%= f.password_field :password, class: 'form-control', placeholder: "パスワード", autocomplete: "off" %>
      </div>
  
      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード(確認)', class: "label-hidden" %>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "パスワード確認", autocomplete: "off" %>
      </div>
  
      <%= f.submit '登録する', class: 'form-btn2' %>
    <% end %>
    
    <%= link_to 'ログイン', login_path %>
  </div>
</div>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>
<P id="alert"><%= alert %></P>
<div>
  <div class="show-all">
    <div class="show-display">
      <div class="back-left">
        <%= link_to '戻る', root_path, class: "back-btn" %>
      </div>
      <div class="user-left">
        <%= link_to "ユーザー変更",edit_admin_user_path(@user), class: "user-btn" %>
      </div>
    </div>
    <h1><a href="/"><%= image_tag "/images/denunce.png", class: "logo" %></a></h1>
    <h1>MYページ</h1>
    <hr>
    <div class="show-display">
      <div>
        <h2>ユーザー</h2>
        <table>
          <tbody>
            <tr>
              <th>ニックネーム</th>
              <td><%= @user.nickname %></td>
            </tr> 
            <tr>
              <th>メールアドレス</th>
              <td><%= @user.email %></td>
            </tr> 
          </tbody>
        </table>
      </div>
      <div>
        <h4>ユーザーの愚痴の投稿割合</h4>
        <%= pie_chart @posts.eager_load(:category).group(:"categories.name").count %>
      </div>
    </div>
    
    <h2>投稿一覧</h2>
    <hr>
    <% @posts.each do |post| %>
      <div style="border-bottom: solid 1px #a9a9a9;" id="post_<%= post.id %>">
        <div class="post-display">
          <div><p><%= safe_join(post.content.split("\n"),tag(:br)) %></p></div>
          <div>
            <%= link_to post, method: :delete, data: { confirm: '削除していいですか?' } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <h2>いいねした投稿</h2>
    <% @likes.each do |like| %>
      <div style="border-bottom: solid 1px #a9a9a9;" id="like_<%= like.id %>">
        <% post = Post.find_by(id: like.post_id) %>
          <div style="padding: 20px;"><P><%= safe_join(post.content.split("\n"),tag(:br)) %></P></div>
      </div>
    <% end %>
    <div class="user-destroy-btn">
      <%= link_to 'アカウント削除', [:admin, @user], method: :delete, data: { confirm: "ユーザ「#{@user.nickname}」を削除します。よろしいですか？" }, class: "user-btn" %>
    </div>
  </div>
</div>