config/routes.rb
Rails.application.routes.draw do
  # login
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'mypage/:id/edit', to: 'sessions#edit', as: 'edit_mypage'
  get 'mypage/:id', to: 'sessions#show', as: 'mypage'
  patch 'mypage/:id', to: 'sessions#update' 
  put 'mypage/:id', to: 'sessions#update'
  
  #likes
  get 'likes' => "likes#index"
  post 'likes' =>"likes#post_create"
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  
  #search
  get 'search' => "searches#search"
  post 'search' =>"searches#create"
  
  #good
  get 'good' => "goods#good" 
  post 'good' => 'goods#create'
  
  #admin
  namespace :admin do
    resources :users
  end
  
  resources :posts 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
end

app/views/layouts/_header.html.erb
<header class="page-header">
  <h1><a href="/"><%= image_tag "/images/denunce.png", class: "logo" %></a></h1>
  <div class="search-form">
    <%= form_with url: search_path, method: :get, local: :true do |f| %>
      <%= f.text_field :keyword, placeholder: "投稿を検索してください" %>
    <% end %>
  </div>
  <div id="hamburger">
    <p class="btn-gNav">
      <span></span>
      <span></span>
      <span></span>
    </p>
    <nav id="gNav" class="">
      <ul class="header-nav gNav-menu">
        <% if session[:user_id].present? %>
          <li>
            <%= link_to 'ログアウト', logout_path, method: :delete %>
          </li>
          <li>
            <%= link_to 'MYページ', admin_user_path(session[:user_id]) %>
          </li>
          <li>
            <div id="open">
              <%= link_to '投稿', new_post_path, remote: true %>
            </div>
            <div class="popup">
              <div class="content">
                <%= link_to '×', posts_path, class: "js-modal-close btn-batu", remote: true %>
                <%= render 'posts/form', post: @post %>
              </div>
            </div>
          </li>
        <% else %>
          <li>
            <%= link_to 'サインイン', new_admin_user_path %>
          </li>
          <li>
            <%= link_to 'ログイン', login_path %>
          </li>
          <li>
            <div id="open">
              <%= link_to '投稿', new_post_path, remote: true %>
            </div>
            <div class="popup">
              <div class="content">
                <%= link_to '×', posts_path, class: "js-modal-close btn-batu", remote: true %>
                <%= render 'posts/form', post: @post %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<div class="subheader">
  <div class="container">
    <div class="underheader">
      <span class="publicnav">
        <span><%= link_to "ホーム", root_path %></span>
        <span><%= link_to "おすすめ投稿", good_path %></span>
        <span><%= link_to "いいねランキング", likes_path %></span>
      </span>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Denunce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>